#Jekyll configuration file

#Build configuration, see http://jekyllrb.com/docs/configuration/#default-configuration
# auto: true
# server: true
highlighter: rouge
markdown: kramdown
kramdown:
  extensions: [smart]

url: "https://learnosm.org/"

#Permalink structure, see http://jekyllrb.com/docs/permalinks/
permalink: /:categories/:title/

#Front Matter, see http://jekyllrb.com/docs/configuration/#front-matter-defaults
columnist:
  paths:
  - _posts

#serving the site, see http://jekyllrb.com/docs/configuration/#default-configuration or http://jekyllrb.com/docs/github-pages/#project-page-url-structure
baseurl: '' #does not include host name

#Prose configurations, see https://github.com/prose/prose/wiki/Prose-Configuration

prose:
  rooturl: '_posts'
  siteurl: "https://learnosm.org/"
  media: 'images'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

# ranking of other guides in the navigation bar
priorities:
  - beginner
  - josm
  - coordination
  - mobile-mapping
  - osm-data
  - hot-tips
  - resources

#translations
translations:
  en:
    language: "English"
    tagline: "Learn OpenStreetMap Step by Step"
    contribute: "Help improve our guides"
    trainingspan: "Are you a workshop organizer?"
    training: "Check out training material for this guide (in English)"
    feedbackspan: "Was this chapter helpful?"
    feedback: "Let us know and help us improve the guides!"
    getstarted: "Get started"
    returntotop: "Return to top of page"
    quickaccess: "Quick access"
  cs:
    tagline: "Naučte se OpenStreetMap krok za krokem"
    contribute: "Pomozte vylepšit naše průvodce"
    trainingspan: "Organizujete workshopy?"
    training: "Podívejte se na cvičební materiál k tomuto návodu (anglicky)"
    feedbackspan: "Byla tato kapitola užitečná?"
    feedback: "Napište nám a pomozte vylepšit naše návody!"
    getstarted: "Začínáme"
    language: "Česky"
    quickaccess: "Rychlý přístup"
    returntotop: "Návrat na začátek stránky"
  de:
    tagline: "OpenStreetMap Schritt für Schritt lernen"
    contribute: "Hilfe bei der Verbesserung unserer Anleitungen"
    trainingspan: "Organisieren Sie Workshops?"
    training: "Befassen Sie sich mit dem (englischsprachigen) Trainingsmaterial für diese Anleitung"
    feedbackspan: "War dieses Kapitel hilfreich?"
    feedback: "Melden Sie sich und helfen Sie, die Anleitungen zu verbessern!"
    getstarted: "Legen Sie los"
    language: "Deutsch"
    quickaccess: "Schnellzugriff"
    returntotop: "Zum Anfang der Seite springen"
  es:
    tagline: "Aprenda OpenStreetMap paso a paso"
    contribute: "Ayude a mejorar nuestras guías"
    trainingspan: "¿Eres un organizador de talleres?"
    training: "Eche un vistazo al material de formación para esta guía"
    feedbackspan: "¿Fue útil este capítulo?"
    feedback: "¡Háganos saber y ayúdenos a mejorar las guías!"
    getstarted: "Comience"
    language: "Español"
    quickaccess: "Acceso rápido"
    returntotop: "Regresar al inicio de la página"
  fa:
    tagline: "OpenStreetMap را گام‌به‌گام بیاموزید"
    contribute: "به بهبود راهنماهای ما کمک کنید"
    trainingspan: "آیا مسئول برگزاری کارگاه آموزشی هستید؟"
    training: "موارد آموزشی این راهنما را به زبان (انگلیسی) ببینید."
    feedbackspan: "این فصل مفید بود؟"
    feedback: "به ما بگویید و کمک کنید راهنماها را بهتر کنیم!"
    getstarted: "شروع به کار"
    language: "فارسی"
    quickaccess: "دسترسی سریع"
    returntotop: "بازگشت به ابتدای صفحه"
  fr:
    tagline: "Apprendre OpenStreetMap étape par étape"
    contribute: "Aidez-nous pour améliorer cette documentation"
    trainingspan: "Organisez-vous des ateliers de cartographie ?"
    training: "Check out training material for this guide (in English)"
    feedbackspan: "Cette page était-elle utile ?"
    feedback: "Faîtes-nous savoir comment améliorer ces guides !"
    getstarted: "Commencer"
    language: "Français"
    quickaccess: "Accès rapide"
    returntotop: "Retourner en haut de la page"
  hu:
    tagline: "Az OpenStreetMap megtanulása lépésről lépésre"
    contribute: "Segíts az útmutatók javításában"
    trainingspan: "Tanfolyamot szervezel?"
    training: "Nézd meg az ehhez az útmutatóhoz tartozó képzési anyagot (angol)"
    feedbackspan: "Hasznos volt-e ez a fejezet?"
    feedback: "Írd meg az észrevételeid, és segíts, hogy tovább javíthassuk az útmutatókat!"
    getstarted: "Kezdés"
    language: "Magyar"
    quickaccess: "Gyors elérés"
    returntotop: "Vissza az oldal tetejére"
  id:
    tagline: "Pelajari OpenStreetMap Langkah demi Langkah"
    contribute: "Bantu memperbaiki panduan OSM"
    trainingspan: "Apakah Anda seorang penyelenggara lokakarya"
    training: "Lihat materi pelatihan untuk panduan ini"
    feedbackspan: "Apakah bab ini bermanfaat?"
    feedback: "Beri tahu kami, dan bantu kami memperbaiki panduan OSM!"
    getstarted: "Memulai"
    language: "bahasa Indonesia"
    quickaccess: "Akses cepat"
    returntotop: "Kembali ke bagian atas halaman"
  it:
    tagline: "Impara ad usare OpenStreetMap passo dopo passo"
    contribute: "Aiutaci a migliorare le nostre guide"
    trainingspan: "Sei un organizzatore di seminari?"
    training: "Dai uno sguardo al materiale di formazione per questa guida (in italiano)"
    feedbackspan: "Questo capitolo è stato utile?"
    feedback: "Dacci il tuo parere ed aiutaci a migliorare le guide!"
    getstarted: "Cominciamo"
    language: "Italiano"
    quickaccess: "Accesso veloce"
    returntotop: "Ritorna ad inizio pagina"
  ja:
    language: "日本語"
    tagline: "はじめてからのOpenStreetMapガイド"
    contribute: "ガイドの拡充にご協力ください"
    trainingspan: "ワークショップを主催されるかたはこちら?"
    training: "このガイドのトレーニング教材はこちら (英語)"
    feedbackspan: "この章はわかりやすかったでしょうか？"
    feedback: "分かりづらかったポイントがあれば教えていただけると幸いです"
    getstarted: "はじめる"
    returntotop: "トップページに戻る"
    quickaccess: "クイックアクセス"
  ko:
    language: "한국어"
    tagline: "단계별 OpenStreetMap 배우기"
    contribute: "안내서를 개선하는 데 도움을 주세요"
    trainingspan: "워크숍 주최자인가요?"
    training: "이 안내서의 교육 내용을 확인하세요(영어)"
    feedbackspan: "이 단락이 도움이 되었나요?"
    feedback: "안내서를 개선하는 걸 도와주고 싶다면 우리에게 알려 주세요!"
    getstarted: "시작하기"
    returntotop: "페이지 맨 위로 돌아가기"
    quickaccess: "빠른 접근"
  my:
    tagline: "OpenStreetMap အားတစ်ဆင့်ပြီးတစ်ဆင့်လေ့လာခြင်း"
    contribute: "ကျွန်ုပ်တို့၏လမ်းညွှန်မှုများတိုးတက်အောင်ကူညီပါ။"
    trainingspan: "သင်သည် အလုပ်ရုံဆွေးနွေးပွဲအတွက်ဖြစ်မြောက်အောင်ဆောင်ရွက်သူတစ်ဦးဖြစ်ပါသလား။"
    training: "ဤလမ်းညွှန်ချက်အတွက်လေ့ကျင့်ရေးပစ္စည်းများကိုစစ်ဆေးပါ။ (အင်္ဂလိပ်ဘာသာဖြင့်)"
    feedbackspan: "ဤအခန်းသည် သင့်အတွက်အထောက်အကူပြုပါသလား။"
    feedback: "ကျွန်ုပ်တို့၏လမ်းညွှန်မှုများကိုတိုးတက်ကောင်းမွန်စေရန် ကျွန်ုပ်တို့အားအသိပေးခြင်းဖြင့်ကူညီပါ။"
    getstarted: "စတင်ရန်"
    language: "ဗမာ"
    quickaccess: "ယခုပဲ အမြန်ဝင်ရောက်လိုက်ပါ။"
    returntotop: "စာမျက်နှာ၏ထိပ်သို့ပြန်သွားပါ။"
  nb:
    tagline: "Lære OpenStreetMap steg for steg"
    contribute: "Hjelp oss med å forbedre våre veiledninger"
    trainingspan: "Organiserer du workshops?"
    training: "Ta en titt på læringsmateriellet for denne guiden (på engelsk)"
    feedbackspan: "Var dette kapitellet til nytte?"
    feedback: "Gi oss tilbakemelding og hjelp oss med å forbedre veilederne"
    getstarted: "Kom i gang"
    language: "Norsk"
    quickaccess: "Hurtigtilgang"
    returntotop: "Gå til toppen av siden"
  nl_NL:
    tagline: "Ontdek de mogelijkheden van OpenStreetMap"
    contribute: "Meehelpen met het verbeteren van handleidingen"
    trainingspan: "Workshops organizeren?"
    training: "Materiaal voor deze handleiding (in het Engels)"
    feedbackspan: "Was dit een goede handleiding?"
    feedback: "Laat ons weten hoe we de handleidingen kunnen verbeteren!"
    getstarted: "Beginnen"
    language: "Nederlands"
    quickaccess: "Snelle toegang"
    returntotop: "Terug naar begin van de pagina"
  pl:
    tagline: "Naucz się OpenStreetMap krok po kroku"
    contribute: "Pomóż w ulepszaniu naszych przewodników"
    trainingspan: "Czy jesteś organizatorem warsztatów?"
    training: "Zobacz materiały szkoleniowe dla tego przewodnika (w języku angielskim)"
    feedbackspan: "Czy ten rozdział był pomocny?"
    feedback: "Daj nam znać i pomóż w ulepszeniu przewodników!"
    getstarted: "Rozpocznij"
    language: "Polski"
    returntotop: "Powrót na górę strony"
    quickaccess: "Szybki dostęp"
  pt:
    tagline: "Aprenda o OpenStreetMap Passo a Passo"
    contribute: "Ajude a melhorar os nossos guias"
    trainingspan: "É um organizador de workshops?"
    training: "Consulte os nossos materiais de apoio para este guia (em inglês)"
    feedbackspan: "Este capítulo foi útil?"
    feedback: "Diga-nos e ajude-nos a melhorar os guias!"
    getstarted: "Começar"
    language: "Português"
    quickaccess: "Acesso rápido"
    returntotop: "Voltar ao início da página"
  ru:
    tagline: "Изучаем OpenStreetMap шаг за шагом"
    contribute: "Помогите улучшить наши руководства"
    trainingspan: "Вы организатор?"
    training: "Смотрите наши обучающие материалы по данному руководству (на английском)"
    feedbackspan: "Был ли данный раздел полезным?"
    feedback: "Дайте нам знать и помогите улучшить руководства!"
    getstarted: "Начало"
    language: "Русский"
    quickaccess: "Быстрый доступ"
    returntotop: "В начало страницы"
  sq:
    tagline: "Mësoni OpenStreetMap hap pas hapi"
    contribute: "Na ndihmoni të përmirësojmë guidën tonë"
    trainingspan: "Jeni një organizator workshopesh (punëtorish) ?"
    training: "Kontrolloni  materialin trajnues për këtë guidë (në Shqip)"
    feedbackspan: "Ishte ky kapitull i dobishëm?"
    feedback: "Na bëni me dije dhe na ndihmoni të përmirësojmë guidat!"
    getstarted: "Fillo"
    language: "Shqip"
    quickaccess: "Qasje e shpejtë"
    returntotop: "Kthehuni në krye të faqes"
  uk:
    language: "Українська"
    tagline: "Знайомимось з OpenStreetMap крок за кроком"
    contribute: "Допоможіть покращити наші посібники"
    trainingspan: "Ви організовуєте семінар?"
    training: "Ознайомтесь із навчальними матеріалами до цього посібника (англійською)"
    feedbackspan: "Чи був цей розділ корисним?"
    feedback: "Дайте нам знати та допоможіть нам покращити цей посібник!"
    getstarted: "Почнімо"
    returntotop: "Повернутись до початку сторінки"
    quickaccess: "Швидкий доступ"
  vi:
    tagline: "Từng bước học OpenStreetMap"
    contribute: "Giúp chúng tôi cải thiện những hướng dẫn này"
    trainingspan: "Bạn có phải là người tổ chức các hội thảo?"
    training: "Kiểm tra các tài liệu tập huấn với hướng dẫn này"
    feedbackspan: "Chương này có bổ ích hay không?"
    feedback: "Hãy cho chúng tôi biết và giúp chúng tôi cỉa thiện những hướng dẫn này!"
    getstarted: "Hãy bắt đầu"
    language: "Tiếng Việt"
    quickaccess: "Truy cập nhanh"
    returntotop: "Quay về đầu trang"
  zh_CN:
    tagline: "逐步学习OpenStreetMap"
    contribute: "帮助改进我们的指南"
    trainingspan: "是工作小组组织者吗？"
    training: "查看本指南的训练材料(英文)"
    feedbackspan: "本章节有用吗？"
    feedback: "告诉我们并帮助我们改进本指南。"
    getstarted: "入门"
    language: "简体中文"
    quickaccess: "Quick access"
    returntotop: "Return to top of page"
  zh_TW:
    tagline: "一步一腳印學習開放街圖"
    contribute: "幫忙改進我們的指南"
    trainingspan: "你是工作坊活動組織者嗎？"
    training: "查看本指南的訓練資料（英文）"
    feedbackspan: "這個章節有用嗎？"
    feedback: "讓我們了解以便我們改進這個指南！"
    getstarted: "入門"
    language: "繁體中文"
    quickaccess: "快速連結"
    returntotop: "回到頁面頂端"

# Save this for later use - these languages are not yet installed

#  ar:
#    tagline: "تعلم OpenStreetMap خطوة بخطوة"
#    contribute: "ساعد في تحسين دلائلنا"
#    trainingspan: "هل أنت منظم ورشة عمل؟"
#    training: "تحقق من المواد التدريبية لهذا الدليل (بالإنجليزية)"
#    feedbackspan: "هل كان هذا الفصل مفيدا؟"
#    feedback: "دعونا نعرف وساعدونا في تحسين دلائلنا!"
#    getstarted: "البدء"
#    language: "العربية"
#    quickaccess: "ولوج سريع"
#    returntotop: "رجوع الى أعلى الصفحة"
#  bn_BD:
#    language: "বাংলা"
#    tagline: "OpenStreetMap ধাপে ধাপে শিখুন"
#    contribute: "আমাদের গাইডগুলো উন্নত করতে সহযোগিতা করুন"
#    trainingspan: "আপনি কি workshop সংগঠক?"
#    training: "এই গাইডের জন্য প্রশিক্ষণ material লক্ষ্য করুন ( ইংরেজিতে )"
#    feedbackspan: "এই অধ্যায় কি উপকারি  ছিল?"
#    feedback: "আমাদেরকে জানাতে এবং আমাদের গাইডগুলো উন্নত করতে সহযোগিতা করুন !"
#    getstarted: "শুরু করা যাক"
#    returntotop: "পৃষ্ঠার শুরুতে ফিরে যান"
#    quickaccess: "দ্রুত প্রবেশ"
#  ca:
#    tagline: "Apreneu sobre l'OpenStreetMap pas a pas"
#    contribute: "Ajudeu-nos a millorar les guies"
#    trainingspan: "Organitzeu tallers?"
#    training: "Feu una ullada al nostre material de formació per a aquesta guia (en anglès)"
#    feedbackspan: "Aquest capítol ha estat útil?"
#    feedback: "Feu-nos ho saber i ajudeu-nos a millorar les guies!"
#    getstarted: "Iniciació"
#    language: "Català"
#    quickaccess: "Accés ràpid"
#    returntotop: "Torna a la part superior de la pàgin"
#  he:
#    language: "עברית"
#    tagline: "רכישת ידע על OpenStreetMap שלב אחר שלב"
#    contribute: "סיוע בשיפור המדריכים שלנו"
#    trainingspan: "תפקידך הוא לארגן סדנאות?"
#    training: "להלן חומרי תרגול עבור מדריך זה (באנגלית)"
#    feedbackspan: "פרק זה סייע לך?"
#    feedback: "נשמח לחוות הדעת שלך ולסיוע שלך לשפר את המדריכים האלה!"
#    getstarted: "איך מתחילים"
#    returntotop: "חזרה לראש העמודge"
#    quickaccess: "גישה מהירה"
#  kn:
#    tagline: "ಹಂತ ಹಂತವಾಗಿ ಒಪನ್‌ಸ್ಟ್ರೀಟ್‌ಮ್ಯಾಪ್ ಕಲಿಯಿರಿ"
#    contribute: "ನಮ್ಮ ಕೈಪಿಡಿಯನ್ನು ಉತ್ತಮಗೊಳಿಸಲು ಸಹಾಯ ಮಾಡಿ"
#    trainingspan: "ನೀವು ಒಪನ್‌ಸ್ಟ್ರೀಟ್‌ಮ್ಯಾಪ್ ಕಾರ್ಯಾಗಾರದ ಆಯೋಜಕರೇ?"
#    training: "ಈ ಕೈಪಿಡಿಯ ತರಬೇತಿ ಪಠ್ಯವನ್ನು ನೋಡಿ(ಇಂಗ್ಲೀಷಿನಲ್ಲಿ)"
#    feedbackspan: "ಈ ಅಧ್ಯಾಯವು ಉಪಯುಕ್ತವಾಗಿದೆಯೆ?"
#    feedback: "ಕೈಪಿಡಿಗಳನ್ನು ಉತ್ತಮಗೊಳಿಸಲು ನಮಗೆ ಸಹಾಯ ಮಾಡಿ ಮತ್ತು ನಿಮ್ಮ ಅಭಿಪ್ರಾಯ ತಿಳಿಸಿರಿ"
#    getstarted: "ಪ್ರಾರಂಭಿಸಿ"
#    language: "ಕನ್ನಡ"
#    quickaccess: "Quick access"
#    returntotop: "Return to top of page"
#  sl:
#    tagline: "Naučite se uporabljati OpenStreetMap Korak za korakom"
#    contribute: "Pomagajte nam izboljšati naše vodiče"
#    trainingspan: "Ali ste organizator delavnic?"
#    training: "Preglejte učno gradivo tega vodiča (v angleškem jeziku)"
#    feedbackspan: "Ali vam je bilo to poglavje v pomoč?"
#    feedback: "Sporočite nam, kako lahko izboljšamo vodiče!"
#    getstarted: "Začnite"
#    language: "Slovenščina"
#    quickaccess: "Hitri dostop"
#    returntotop: "Vrnite se na vrh strani"

