#Jekyll configuration file

#Build configuration, see http://jekyllrb.com/docs/configuration/#default-configuration
# auto: true
# server: true
highlighter: rouge
markdown: kramdown
kramdown:
  extensions: [smart]

url: "http://learnosm.org/"

#Permalink structure, see http://jekyllrb.com/docs/permalinks/
permalink: /:categories/:title/

#Front Matter, see http://jekyllrb.com/docs/configuration/#front-matter-defaults
columnist:
  paths:
  - _posts

#serving the site, see http://jekyllrb.com/docs/configuration/#default-configuration or http://jekyllrb.com/docs/github-pages/#project-page-url-structure
baseurl: '' #does not include host name

#Prose configurations, see https://github.com/prose/prose/wiki/Prose-Configuration
prose:
  rooturl: '_posts'
  siteurl: "http://learnosm.org/"
  media: 'images'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes

gems:
  - jekyll-redirect-from

#translations
translations:
  en:
    language: "English"
    tagline: "Learn OpenStreetMap Step by Step"
    contribute: "Help improve our guides"
    trainingspan: "Are you a workshop organizer?"
    training: "Check out training material for this guide (in English)"
    feedbackspan: "Was this chapter helpful?"
    feedback: "Let us know and help us improve the guides!"
    getstarted: "Get started"
    returntotop: "Return to top of page"
    quickaccess: "Quick access"
  cs:
    language: "Česky"
    tagline: "Naučte se OpenStreetMap krok za krokem"
    contribute: "Pomožte vylepšit naše průvodce"
    trainingspan: "Organizujete workshopy?"
    training: "Podívejte se na cvičební materiál k tomuto návodu (anglicky)"
    feedbackspan: "Byla tato kapitola užitečná?"
    feedback: "Napište nám a pomožte nám zlepšit naše návody!"
    getstarted: "Začínáme"
    returntotop: "Return to top of page"
    quickaccess: "Quick access"
  de:
    tagline: "OpenStreetMap Schritt für Schritt lernen"
    contribute: "Hilfe bei der Verbesserung unserer Anleitungen"
    trainingspan: "Organisieren Sie Workshops?"
    training: "Befassen Sie sich mit dem (englischsprachigen) Trainingsmaterial für diese Anleitung"
    feedbackspan: "War dieses Kapitel hilfreich?"
    feedback: "Melden Sie sich und helfen Sie, die Anleitungen zu verbessern!"
    getstarted: "Legen Sie los"
    language: "Deutsch"
    quickaccess: "Schnellzugriff"
    returntotop: "Zum Anfang der Seite springen"
  es:
    tagline: "Aprenda OpenStreetMap paso a paso"
    contribute: "Ayude a mejorar nuestras guías"
    trainingspan: "¿Eres un organizador de talleres?"
    training: "Eche un vistazo al material de formación para esta guía"
    feedbackspan: "¿Fue útil este capítulo?"
    feedback: "¡Háganos saber y ayúdenos a mejorar las guías!"
    getstarted: "Comience"
    language: "Español"
    quickaccess: "Acceso rápido"
    returntotop: "Regresar al inicio de la página"
  fa:
    language: "فارسی"
    tagline: "آموزش گام به گام OpenStreetMap"
    contribute: "به بهبود راهنماهای ما کمک کنید"
    trainingspan: "آیا مسئول برگزاری کارگاه آموزشی هستید؟"
    training: "موارد آموزشی این راهنما را به زبان (انگلیسی) ببینید."
    feedbackspan: "آیا این بخش مفید بود؟"
    feedback: "با ما درمیان بگذارید و راهنماها را بهبود ببخشید!"
    getstarted: "شروع به کار"
    returntotop: "Return to top of page"
    quickaccess: "Quick access"
  fr:
    tagline: "Apprendre OpenStreetMap étape par étape"
    contribute: "Aidez-nous pour améliorer cette documentation"
    trainingspan: "Organisez-vous des ateliers de cartographie ?"
    training: "Check out training material for this guide (in English)"
    feedbackspan: "Cette page était-elle utile ?"
    feedback: "Faîtes-nous savoir comment améliorer ces guides !"
    getstarted: "Commencer"
    language: "Français"
    quickaccess: "Accès rapide"
    returntotop: "Retourner en haut de la page"
  hr:
    language: "Hrvatski"
    tagline: "Naučite OpenStreetMap korak po korak"
    contribute: "Pomozite poboljšati naša uputstva"
    trainingspan: "Organizirate li radionicu?"
    training: "Vidi trening materijale za ova uputstva(na engleskom)"
    feedbackspan: "Je li ovo poglavlje bilo korisno?"
    feedback: "Javite nam i pomozite nam poboljšati uputstva!"
    getstarted: "Započnite"
    returntotop: "Return to top of page"
    quickaccess: "Quick access"
  id:
    language: "Bahasa Indonesia"
    overview: "Ringkasan"
    tagline: "Pelajari OpenStreetMap Langkah Demi Langkah"
    contribute: "Bantu tingkatkan panduan kami!"
    trainingspan: "Apakah Anda seorang pengelola lokakarya?"
    training: "Periksa materi pelatihan untuk panduan ini (dalam bahasa Inggris)"
    feedbackspan: "Apakah bab ini bermanfaat?"
    feedback: "Beritahu kami dan bantu kami memperbaiki panduan!"
    getstarted: "Lanjutkan ke bab berikutnya"
    returntotop: "Return to top of page"
    quickaccess: "Quick access"
  it:
    language: "Italiano"
    overview: "Riassunto"
    tagline: "Impara a conoscere OpenStreetMap passo dopo passo"
    contribute: "Aiutaci a migliorare le nostre guide!"
    trainingspan: "Sei un organizzatore di workshop?"
    training: "Scopri materiale formativo per la guida principianti (in inglese)"
    feedbackspan: "Questa capitolo ti è stato utile?"
    feedback: "Contattaci ed aiutaci a migliorare le guide!"
    getstarted: "procedere al capitolo successivo"
    returntotop: "Return to top of page"
    quickaccess: "Quick access"
  ja:
    language: "日本語"
    overview: "概要"
    tagline: "はじめてからのOpenStreetMapガイド"
    contribute: "ガイドの拡充にご協力ください"
    trainingspan: "ワークショップ開催を検討されるかたへ"
    training: "このガイドの研修教材をチェック(英語)"
    feedbackspan: "この章は役に立ちましたか？"
    feedback: "ガイドの改善にご意見ください"
    getstarted: "次の章に進む"
    returntotop: "Return to top of page"
    quickaccess: "Quick access"
  my:
    language: "ဗမာ"
    tagline: "OpenStreetMap အားတစ်ဆင့်ပြီးတစ်ဆင့်လေ့လာခြင်း"
    contribute: "ကျွန်ုပ်တို့၏လမ်းညွှန်မှုများတိုးတက်အောင်ကူညီပါ။"
    trainingspan: "သင်သည် အလုပ်ရုံဆွေးနွေးပွဲအတွက်ဖြစ်မြောက်အောင်ဆောင်ရွက်သူတစ်ဦးဖြစ်ပါသလား။"
    training: "ဤလမ်းညွှန်ချက်အတွက်လေ့ကျင့်ရေးပစ္စည်းများကိုစစ်ဆေးပါ။ (အင်္ဂလိပ်ဘာသာဖြင့်)"
    feedbackspan: "ဤအခန်းသည် သင့်အတွက်အထောက်အကူပြုပါသလား။"
    feedback: "ကျွန်ုပ်တို့၏လမ်းညွှန်မှုများကိုတိုးတက်ကောင်းမွန်စေရန် ကျွန်ုပ်တို့အားအသိပေးခြင်းဖြင့်ကူညီပါ။"
    getstarted: "စတင်ရန်"
    returntotop: "Return to top of page"
    quickaccess: "Quick access"
  nl:
    language: "Nederlands"
    tagline: "Ontdek de mogelijkheden van OpenStreetMap"
    contribute: "Meehelpen met het verbeteren van handleidingen"
    trainingspan: "Workshops organizeren?"
    training: "Materiaal voor deze handleiding (in het engels)"
    feedbackspan: "Was dit een goede handleiding?"
    feedback: "Laat ons weten hoe we de handleidingen kunnen verbeteren!"
    getstarted: "Beginnen"
    returntotop: "Terug naar begin van de pagina"
    quickaccess: "Snelle toegang"
  nb:
    language: "Norsk"
    tagline: "Lær deg OpenStreetMap steg for steg"
    contribute: "Hjelpe oss å forbedre våre guider"
    trainingspan: "Kan du hjelpe til med å organisere workshops?"
    training: "Se her for øvelser for denne guiden (på norsk)"
    feedbackspan: "Var dette kapittelet nyttig?"
    feedback: "Gi oss tilbakemelding og hjelp oss med å forbedre guidene!"
    getstarted: "Kom i gang"
    returntotop: "Gå til toppen av siden"
    quickaccess: "Hurtigtilgang"
  pt:
    language: "Português"
    overview: "Sumário"
    tagline: "Conheça sobre o OpenStreetMap, passo-a-passo."
    contribute: "Ajude-nos a melhorar os nossos guias!"
    trainingspan: "Você é um organizador de workshop?"
    training: "Confira material de treinamento para este guia (em Inglês)"
    feedbackspan: "Este capítulo foi útil?"
    feedback: "Conte-nos e ajude a melhorar os guias!"
    getstarted: "prosseguir para o próximo capítulo"
    returntotop: "Return to top of page"
    quickaccess: "Quick access"
  ru:
    language: "Русский"
    tagline: "Изучаем OpenStreetMap шаг за шагом"
    contribute: "Помогите улучшить наши руководства"
    trainingspan: "Вы организатор?"
    training: "Смотрите наши обучающие материалы по данному руководству (на английском)"
    feedbackspan: "Был ли данный раздел полезным?"
    feedback: "Дайте нам знать и помогите улучшить руководства!"
    getstarted: "Начало"
    returntotop: "В начало страницы"
    quickaccess: "Быстрый доступ"
  sq:
    tagline: "Mësoni OpenStreetMap hap pas hapi"
    contribute: "Na ndihmoni të përmirësojmë guidën tonë"
    trainingspan: "Jeni një organizator workshopesh (punëtorish) ?"
    training: "Kontrolloni  materialin trajnues për këtë guidë (në Shqip)"
    feedbackspan: "Ishte ky kapitull i dobishëm?"
    feedback: "Na bëni me dije dhe na ndihmoni të përmirësojmë guidat!"
    getstarted: "Fillo"
    language: "Shqip"
    quickaccess: "Qasje e shpejtë"
    returntotop: "Kthehuni në krye të faqes"
  sw:
    language: "Kiswahili"
    tagline: "Jifunze OpenStreetMap hatua kwa hatua"
    contribute: "Saidia kuboresha miongozo yetu"
    trainingspan: "Je wewe ni muaandaaji wa mkutano?"
    training: "Angalia mafundisho ya huu muongozo(kwa kiingereza)"
    feedbackspan: "Je hii sura ilikuwa na manufaa?"
    feedback: "Tujulishe na utusaidie kuboresha miongozo!"
    getstarted: "Anza"
    returntotop: "Return to top of page"
    quickaccess: "Quick access"
  uk:
    language: "Українська"
    tagline: "Знайомимось з OpenStreetMap крок за кроком"
    contribute: "Допоможіть покращити наші посібники"
    trainingspan: "Ви проводите семінар?"
    training: "Ознайомтесь з навчальними матеріалами для цього посібника (англ.)"
    feedbackspan: "Чи був цей розділ корисним?"
    feedback: "Повідомте нам і допоможіть нам покращити посібник!"
    getstarted: "Розпочати"
    returntotop: "Return to top of page"
    quickaccess: "Quick access"
  zh:
    language: "简体中文"
    tagline: "逐步学习OpenStreetMap"
    contribute: "帮助改进我们的指南"
    trainingspan: "是工作小组组织者吗？"
    training: "查看本指南的训练材料(英文)"
    feedbackspan: "本章节有用吗？"
    feedback: "告诉我们并帮助我们改进本指南。"
    getstarted: "入门"
    returntotop: "Return to top of page"
    quickaccess: "Quick access"
  zh-tw:
    language: "繁體中文"
    tagline: "一步一腳印學習開放街圖"
    contribute: "幫忙改進我們的指南"
    trainingspan: "你是工作坊活動組織者嗎？"
    training: "查看本指南的訓練資料（英文）"
    feedbackspan: "這個章節有用嗎？"
    feedback: "讓我們了解以便我們改進這個指南！"
    getstarted: "入門"
    returntotop: "回到頁面頂端"
    quickaccess: "快速連結"
