auto: true
pygments: true
server: true
markdown: rdiscount
permalink: /:categories/:title/
columnist:
  paths:
  - _posts
baseurl: ''
rdiscount:
  extensions: [smart]
prose:
  rooturl: '_posts'
translations:
  en:
    tagline: "Learn OpenStreetMap Step by Step"
    contribute: "Help improve our guides"
    trainingspan: "Are you a workshop organizer?"
    training: "Check out training material for this guide (in English)"
    feedbackspan: "Was this chapter helpful?"
    feedback: "Let us know and help us improve the guides!"
    getstarted: "Get started"
  es:
    tagline: "Aprende OpenStreetMap Paso a Paso"
    contribute: "Ayuda a mejorar las guías"
    trainingspan: "¿Eres el organizador de un taller?"
    training: "Revisa nuestros materiales de aprendizaje para esta guía (en inglés)"
    feedbackspan: "¿Este capítulo te resultó útil?"
    feedback: "¡Contacta con nosotros y ayúdanos a mejorar estas guías!"
    getstarted: "Comencemos"
  fr:
    tagline: "Apprendre OpenStreetMap pas à pas"
    contribute: "Contribuer à ces guides"
    trainingspan: "Vous organisez des ateliers ?"
    training: "Consulter le matérial d'apprentissage (en anglais)"
    feedbackspan: "Avez-vous trouvé ce chapitre utile ?"
    feedback: "Aidez-nous à améliorer ces guides en donnant vos impressions!"
    getstarted: "Commencer"
  bi:
    overview: "Ringkasan"
    tagline: "Pelajari OpenStreetMap Langkah Demi Langkah"
    contribute: "Bantu tingkatkan panduan kami!"
    trainingspan: "Apakah Anda seorang pengelola lokakarya?"
    training: "Periksa materi pelatihan untuk panduan ini (dalam bahasa Inggris)"
    feedbackspan: "Apakah bab ini bermanfaat?"
    feedback: "Beritahu kami dan bantu kami memperbaiki panduan!"
    getstarted: "Lanjutkan ke bab berikutnya"
  jp:
    overview: "概要"
    tagline: "はじめてからのOpenStreetMapガイド"
    contribute: "ガイドの拡充にご協力ください"
    trainingspan: "ワークショップ開催を検討されるかたへ"
    training: "このガイドの研修教材をチェック(英語)"
    feedbackspan: "この章は役に立ちましたか？"
    feedback: "ガイドの改善にご意見ください"
    getstarted: "次の章に進む"
  pt:
    overview: "Sumário"
    tagline: "Conheça sobre o OpenStreetMap, passo-a-passo."
    contribute: "Ajude-nos a melhorar os nossos guias!"
    trainingspan: "Você é um organizador de workshop?"
    training: "Confira material de treinamento para este guia (em Inglês)"
    feedbackspan: "Este capítulo foi útil?"
    feedback: "Conte-nos e ajude a melhorar os guias!"
    getstarted: "prosseguir para o próximo capítulo"
  it:
    overview: "Riassunto"
    tagline: "Impara a conoscere OpenStreetMap passo dopo passo"
    contribute: "Aiutaci a migliorare le nostre guide!"
    trainingspan: "Sei un organizzatore di workshop?"
    training: "Scopri materiale formativo per la guida principianti (in inglese)"
    feedbackspan: "Questa capitolo ti è stato utile?"
    feedback: "Contattaci ed aiutaci a migliorare le guide!"
    getstarted: "procedere al capitolo successivo"
  de:
    tagline: "Lerne OpenStreetMap Schritt für Schritt kennen"
    contribute: "Hilf mit, unsere Anleitungen zu verbessern"
    trainingspan: "Veranstaltest du Workshops?"
    training: "Siehr dir unsere Unterlagen für diesen Kurs an (in Englisch)"
    feedbackspan: "War dieses Kapitel hilfreich?"
    feedback: "Sende uns Feedback und verbessere die Anleitungen!"
    getstarted: "weiter zum nächsten Kapitel"
  hr:
    tagline: "Naučite OpenStreetMap korak po korak"
    contribute: "Pomozite poboljšati naša uputstva"
    trainingspan: "Organizirate li radionicu?"
    training: "Vidi trening materijale za ova uputstva(na engleskom)"
    feedbackspan: "Je li ovo poglavlje bilo korisno?"
    feedback: "Javite nam i pomozite nam poboljšati uputstva!"
    getstarted: "Započnite"
