#Jekyll configuration file

#Build configuration, see http://jekyllrb.com/docs/configuration/#default-configuration
# auto: true
# server: true
highlighter: rouge
markdown: kramdown
kramdown:
  extensions: [smart]

url: "http://learnosm.org/"

#Permalink structure, see http://jekyllrb.com/docs/permalinks/
permalink: /:categories/:title/

#Front Matter, see http://jekyllrb.com/docs/configuration/#front-matter-defaults
columnist:
  paths:
  - _posts

#serving the site, see http://jekyllrb.com/docs/configuration/#default-configuration or http://jekyllrb.com/docs/github-pages/#project-page-url-structure
baseurl: '' #does not include host name

#Prose configurations, see https://github.com/prose/prose/wiki/Prose-Configuration

prose:
  rooturl: '_posts'
  siteurl: "http://learnosm.org/"
  media: 'images'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes

gems:
  - jekyll-redirect-from

#translations
translations:
  en:
    language: "English"
    tagline: "Learn OpenStreetMap Step by Step"
    contribute: "Help improve our guides"
    trainingspan: "Are you a workshop organizer?"
    training: "Check out training material for this guide (in English)"
    feedbackspan: "Was this chapter helpful?"
    feedback: "Let us know and help us improve the guides!"
    getstarted: "Get started"
    returntotop: "Return to top of page"
    quickaccess: "Quick access"
  ar:
    tagline: "تعلم OpenStreetMap خطوة بخطوة"
    contribute: "ساعد في تحسين دلائلنا"
    trainingspan: "هل أنت منظم ورشة عمل؟"
    training: "تحقق من المواد التدريبية لهذا الدليل (بالإنجليزية)"
    feedbackspan: "هل كان هذا الفصل مفيدا؟"
    feedback: "دعونا نعرف وساعدونا في تحسين دلائلنا!"
    getstarted: "البدء"
    language: "العربية"
    quickaccess: "ولوج سريع"
    returntotop: "رجوع الى أعلى الصفحة"
  ca:
    tagline: "Apreneu sobre l'OpenStreetMap pas a pas"
    contribute: "Ajudeu-nos a millorar les guies"
    trainingspan: "Organitzeu tallers?"
    training: "Feu una ullada al nostre material de formació per a aquesta guia (en anglès)"
    feedbackspan: "Aquest capítol ha estat útil?"
    feedback: "Feu-nos ho saber i ajudeu-nos a millorar les guies!"
    getstarted: "Iniciació"
    language: "Català"
    quickaccess: "Accés ràpid"
    returntotop: "Torna a la part superior de la pàgin"
  cs:
    tagline: "Naučte se OpenStreetMap krok za krokem"
    contribute: "Pomožte vylepšit naše průvodce"
    trainingspan: "Organizujete workshopy?"
    training: "Podívejte se na cvičební materiál k tomuto návodu (anglicky)"
    feedbackspan: "Byla tato kapitola užitečná?"
    feedback: "Napište nám a pomožte nám zlepšit naše návody!"
    getstarted: "Začínáme"
    language: "Česky"
    quickaccess: "Quick access"
    returntotop: "Return to top of page"
  de:
    tagline: "OpenStreetMap Schritt für Schritt lernen"
    contribute: "Hilfe bei der Verbesserung unserer Anleitungen"
    trainingspan: "Organisieren Sie Workshops?"
    training: "Befassen Sie sich mit dem (englischsprachigen) Trainingsmaterial für diese Anleitung"
    feedbackspan: "War dieses Kapitel hilfreich?"
    feedback: "Melden Sie sich und helfen Sie, die Anleitungen zu verbessern!"
    getstarted: "Legen Sie los"
    language: "Deutsch"
    quickaccess: "Schnellzugriff"
    returntotop: "Zum Anfang der Seite springen"
  es:
    tagline: "Aprenda OpenStreetMap paso a paso"
    contribute: "Ayude a mejorar nuestras guías"
    trainingspan: "¿Eres un organizador de talleres?"
    training: "Eche un vistazo al material de formación para esta guía"
    feedbackspan: "¿Fue útil este capítulo?"
    feedback: "¡Háganos saber y ayúdenos a mejorar las guías!"
    getstarted: "Comience"
    language: "Español"
    quickaccess: "Acceso rápido"
    returntotop: "Regresar al inicio de la página"
  fa:
    tagline: "آموزش گام به گام OpenStreetMap"
    contribute: "به بهبود راهنماهای ما کمک کنید"
    trainingspan: "آیا مسئول برگزاری کارگاه آموزشی هستید؟"
    training: "موارد آموزشی این راهنما را به زبان (انگلیسی) ببینید."
    feedbackspan: "آیا این بخش مفید بود؟"
    feedback: "با ما درمیان بگذارید و راهنماها را بهبود ببخشید!"
    getstarted: "شروع به کار"
    language: "فارسی"
    quickaccess: "دسترسی سریع"
    returntotop: "بازگشت به ابتدای صفحه"
  fr:
    tagline: "Apprendre OpenStreetMap étape par étape"
    contribute: "Aidez-nous pour améliorer cette documentation"
    trainingspan: "Organisez-vous des ateliers de cartographie ?"
    training: "Check out training material for this guide (in English)"
    feedbackspan: "Cette page était-elle utile ?"
    feedback: "Faîtes-nous savoir comment améliorer ces guides !"
    getstarted: "Commencer"
    language: "Français"
    quickaccess: "Accès rapide"
    returntotop: "Retourner en haut de la page"
  it:
    tagline: "Impara ad usare OpenStreetMap passo dopo passo"
    contribute: "Aiutaci a migliorare le nostre guide"
    trainingspan: "Sei un organizzatore di seminari?"
    training: "Dai uno sguardo al materiale di formazione per questa guida (in italiano)"
    feedbackspan: "Questo capitolo è stato utile?"
    feedback: "Dacci il tuo parere ed aiutaci a migliorare le guide!"
    getstarted: "Cominciamo"
    language: "Italiano"
    quickaccess: "Accesso veloce"
    returntotop: "Ritorna ad inizio pagina"
  kn:
    tagline: "ಹಂತ ಹಂತವಾಗಿ ಒಪನ್‌ಸ್ಟ್ರೀಟ್‌ಮ್ಯಾಪ್ ಕಲಿಯಿರಿ"
    contribute: "ನಮ್ಮ ಕೈಪಿಡಿಯನ್ನು ಉತ್ತಮಗೊಳಿಸಲು ಸಹಾಯ ಮಾಡಿ"
    trainingspan: "ನೀವು ಒಪನ್‌ಸ್ಟ್ರೀಟ್‌ಮ್ಯಾಪ್ ಕಾರ್ಯಾಗಾರದ ಆಯೋಜಕರೇ?"
    training: "ಈ ಕೈಪಿಡಿಯ ತರಬೇತಿ ಪಠ್ಯವನ್ನು ನೋಡಿ(ಇಂಗ್ಲೀಷಿನಲ್ಲಿ)"
    feedbackspan: "ಈ ಅಧ್ಯಾಯವು ಉಪಯುಕ್ತವಾಗಿದೆಯೆ?"
    feedback: "ಕೈಪಿಡಿಗಳನ್ನು ಉತ್ತಮಗೊಳಿಸಲು ನಮಗೆ ಸಹಾಯ ಮಾಡಿ ಮತ್ತು ನಿಮ್ಮ ಅಭಿಪ್ರಾಯ ತಿಳಿಸಿರಿ"
    getstarted: "ಪ್ರಾರಂಭಿಸಿ"
    language: "ಕನ್ನಡ"
    quickaccess: "Quick access"
    returntotop: "Return to top of page"
  my:
    tagline: "OpenStreetMap အားတစ်ဆင့်ပြီးတစ်ဆင့်လေ့လာခြင်း"
    contribute: "ကျွန်ုပ်တို့၏လမ်းညွှန်မှုများတိုးတက်အောင်ကူညီပါ။"
    trainingspan: "သင်သည် အလုပ်ရုံဆွေးနွေးပွဲအတွက်ဖြစ်မြောက်အောင်ဆောင်ရွက်သူတစ်ဦးဖြစ်ပါသလား။"
    training: "ဤလမ်းညွှန်ချက်အတွက်လေ့ကျင့်ရေးပစ္စည်းများကိုစစ်ဆေးပါ။ (အင်္ဂလိပ်ဘာသာဖြင့်)"
    feedbackspan: "ဤအခန်းသည် သင့်အတွက်အထောက်အကူပြုပါသလား။"
    feedback: "ကျွန်ုပ်တို့၏လမ်းညွှန်မှုများကိုတိုးတက်ကောင်းမွန်စေရန် ကျွန်ုပ်တို့အားအသိပေးခြင်းဖြင့်ကူညီပါ။"
    getstarted: "စတင်ရန်"
    language: "ဗမာ"
    quickaccess: "ယခုပဲ အမြန်ဝင်ရောက်လိုက်ပါ။"
    returntotop: "စာမျက်နှာ၏ထိပ်သို့ပြန်သွားပါ။"
  nb:
    tagline: "Lære OpenStreetMap steg for steg"
    contribute: "Hjelp oss med å forbedre våre veiledninger"
    trainingspan: "Organiserer du workshops?"
    training: "Ta en titt på læringsmateriellet for denne guiden (på engelsk)"
    feedbackspan: "Var dette kapitellet til nytte?"
    feedback: "Gi oss tilbakemelding og hjelp oss med å forbedre veilederne"
    getstarted: "Kom i gang"
    language: "Norsk"
    quickaccess: "Hurtigtilgang"
    returntotop: "Gå til toppen av siden"
  nl_NL:
    tagline: "Ontdek de mogelijkheden van OpenStreetMap"
    contribute: "Meehelpen met het verbeteren van handleidingen"
    trainingspan: "Workshops organizeren?"
    training: "Materiaal voor deze handleiding (in het Engels)"
    feedbackspan: "Was dit een goede handleiding?"
    feedback: "Laat ons weten hoe we de handleidingen kunnen verbeteren!"
    getstarted: "Beginnen"
    language: "Nederlands"
    quickaccess: "Snelle toegang"
    returntotop: "Terug naar begin van de pagina"
  pt:
    tagline: "Aprenda o OpenStreetMap Passo a Passo"
    contribute: "Ajude a melhorar os nossos guias"
    trainingspan: "É um organizador de workshops?"
    training: "Consulte os nossos materiais de apoio para este guia (em inglês)"
    feedbackspan: "Este capítulo foi útil?"
    feedback: "Diga-nos e ajude-nos a melhorar os guias!"
    getstarted: "Começar"
    language: "Português"
    quickaccess: "Acesso rápido"
    returntotop: "Voltar ao início da página"
  ru:
    tagline: "Изучаем OpenStreetMap шаг за шагом"
    contribute: "Помогите улучшить наши руководства"
    trainingspan: "Вы организатор?"
    training: "Смотрите наши обучающие материалы по данному руководству (на английском)"
    feedbackspan: "Был ли данный раздел полезным?"
    feedback: "Дайте нам знать и помогите улучшить руководства!"
    getstarted: "Начало"
    language: "Русский"
    quickaccess: "Быстрый доступ"
    returntotop: "В начало страницы"
  sl:
    tagline: "Naučite se uporabljati OpenStreetMap Korak za korakom"
    contribute: "Pomagajte nam izboljšati naše vodiče"
    trainingspan: "Ali ste organizator delavnic?"
    training: "Preglejte učno gradivo tega vodiča (v angleškem jeziku)"
    feedbackspan: "Ali vam je bilo to poglavje v pomoč?"
    feedback: "Sporočite nam, kako lahko izboljšamo vodiče!"
    getstarted: "Začnite"
    language: "Slovenščina"
    quickaccess: "Hitri dostop"
    returntotop: "Vrnite se na vrh strani"
  sq:
    tagline: "Mësoni OpenStreetMap hap pas hapi"
    contribute: "Na ndihmoni të përmirësojmë guidën tonë"
    trainingspan: "Jeni një organizator workshopesh (punëtorish) ?"
    training: "Kontrolloni  materialin trajnues për këtë guidë (në Shqip)"
    feedbackspan: "Ishte ky kapitull i dobishëm?"
    feedback: "Na bëni me dije dhe na ndihmoni të përmirësojmë guidat!"
    getstarted: "Fillo"
    language: "Shqip"
    quickaccess: "Qasje e shpejtë"
    returntotop: "Kthehuni në krye të faqes"
  zh_CN:
    tagline: "逐步学习OpenStreetMap"
    contribute: "帮助改进我们的指南"
    trainingspan: "是工作小组组织者吗？"
    training: "查看本指南的训练材料(英文)"
    feedbackspan: "本章节有用吗？"
    feedback: "告诉我们并帮助我们改进本指南。"
    getstarted: "入门"
    language: "简体中文"
    quickaccess: "Quick access"
    returntotop: "Return to top of page"
  zh_TW:
    tagline: "一步一腳印學習開放街圖"
    contribute: "幫忙改進我們的指南"
    trainingspan: "你是工作坊活動組織者嗎？"
    training: "查看本指南的訓練資料（英文）"
    feedbackspan: "這個章節有用嗎？"
    feedback: "讓我們了解以便我們改進這個指南！"
    getstarted: "入門"
    language: "繁體中文"
    quickaccess: "快速連結"
    returntotop: "回到頁面頂端"
